swagger: '2.0'
info:
  title: "E-commerce API"
  description: "This is an API to manage an E-commerce application"
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths: {}
definitions: {}

# "Yet Another Markup Language" => YAML
